### ISSUE TITLE
No option to close out of config.

### ISSUE THREAD

**Issue by stshryu** [rgd87/Aptechka#104]
Not sure if this is an error with my resolution or what kind of bug this is but I'm unable to close out of the aptechka config menu without first reloading my entire UI.
![image](https://user-images.githubusercontent.com/5150823/196224963-54ea3183-0eb0-4f49-a4ad-515cacbd0177.png)
There is no close dialog option, or an `x` dialog option to get out of this modal without reloading my UI or exiting and restarting my game.

**Comment by vendethiel** [comment]
You can actually click the top right corner, but the X doesn't display

**Comment by stshryu** [comment]
You're right, I'm able to click in the top right to close it, odd bug. Thanks for the fix.
