### ISSUE TITLE
Layout Test not working in Dragonflight Prepatch

### ISSUE THREAD

**Issue by FortyOneNY** [rgd87/Aptechka#106]
With only Aptechka, Aptechka Options, BugGrabber, and BugSack enabled, I get the following error whenever I attempt to use the Layout Test feature:

1x Frame:CreateTexture(): Couldn't find inherited node "-5"
[string "=[C]"]: in function `CreateTexture'
[string "@Interface/AddOns/Aptechka/frame.lua"]:3792: in function `CreateFakeGroupHeader'
[string "@Interface/AddOns/Aptechka/frame.lua"]:3810: in function `CreateFakeGroupHeaders'
[string "@Interface/AddOns/Aptechka/frame.lua"]:3819: in function `CycleTestMode'
[string "@Interface/AddOns/Aptechka/frame.lua"]:3852: in function `ToggleTestMode'
[string "@Interface/AddOns/Aptechka/Options/ProfileSettings.lua"]:42: in function <...nterface/AddOns/Aptechka/Options/ProfileSettings.lua:42>
[string "=[C]"]: ?
[string "@Interface/AddOns/Aptechka/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-85/AceConfigDialog-3.0.lua"]:45: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:43>
[string "@Interface/AddOns/Aptechka/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-85/AceConfigDialog-3.0.lua"]:827: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:649>
[string "=[C]"]: ?
[string "@Interface/AddOns/Aptechka/Libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <...rface/AddOns/Aptechka/Libs/AceGUI-3.0/AceGUI-3.0.lua:64>
[string "@Interface/AddOns/Aptechka/Libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Interface/AddOns/Aptechka/Libs/AceGUI-3.0-41/widgets/AceGUIWidget-Button.lua"]:22: in function <...chka/Libs/AceGUI-3.0/widgets/AceGUIWidget-Button.lua:19>

**Comment by d87** [comment]
Thanks for reporting, will be fixed in the next update
