### ISSUE TITLE
zhCN

### ISSUE THREAD

**Issue by JSZMonkey** [rgd87/Aptechka#11]
`
local L = Aptechka.L

if GetLocale() ~= "zhCN" then return end

L["Aptechka Settings"] = "Aptechka 设置"
L["Anchors"] = "锚点"
L["Unlock"] = "解锁"
L["Lock"] = "锁定"
L["Reset"] = "重置"
L["Width"] = "宽度"
L["Height"] = "高度"
L["Name Length"] = "姓名长度"
L["Takes effect after /reload"] = "重新加载后生效（/reload）"
L["Group Growth Direction"] = "小队扩展方向"
L["Left"] = "左"
L["Right"] = "右"
L["Up"] = "上"
L["Down"] = "下"
L["Group Gap"] = "小队间距"
L["Unit Growth Direction"] = "单位扩展方向"
L["Unit Gap"] = "单位间距"
L["Show Solo"] = "显示决斗"
L["Sort Units by Role"] = "按姓名排列"
L["Disable Blizzard Party Frames"] = "禁用暴雪小队框架"
L["Hide Blizzard Raid Frames"] = "隐藏暴雪团队框架"
L["Enable Pet Group"] = "启用宠物分组"
L["Disable Tooltips"] = "禁用提示"
L["Show AFK"] = "显示战离"
-- L["Use LibCLH"] = ""
L["Warning: Requires UI reloading."] = "警告：需要重新加载用户界面。"
L["Use Debuff Ordering"] = "使用负面效果排序"
L["Show Casts"] = "显示施法"
L["Show All Casts"] = "显示所有施法"
L["Health Orientation"] = "血量方向"
L["Horizontal"] = "水平方向"
L["Vertical"] = "垂直方向"
L["Health Texture"] = "血量材质"
-- L["Set the statusbar texture."] = ""
L["Power Texture"] = "能量材质"
L["Font"] = "字体"
L["Name Font Size"] = "姓名字体大小"
L["Name Outline"] = "姓名轮廓"
L["None"] = "空"
L["Shadow"] = "阴影"
L["Outline"] = "轮廓"
L["Debuff Size"] = "负面效果大小"
L["Stack Font Size"] = "堆栈字体大小"
L["Test Debuffs"] = "测试负面效果"
L["Show Missing Health/Power as Foreground"] = "显示损失的 血量/能量 颜色为前景色"
L["Color Multipliers"] = "颜色选择器"
L["Foreground"] = "前景色"
L["Background"] = "背景色"
L["Name"] = "姓名"
L["Full Settings Reset"] = "全局重置"
L["Wipe all your settings and restore to defaults"] = "清除所有设置并还原为默认值"
-- L["Aptechka Autoscaling"] = ""
L["Normal Scale (1-11 players)"] = "一般小队 (1-11 人)"
L["Healer Autoscale"] = "治疗自动缩放"
L["Raid (12-30 players)"] = "团队 (12-30 人)"
L["Big Raid (30+ players)"] = "大型团队 (30+ 人)"
L["Damage Autoscale"] = "伤害自动缩放"
`

**Comment by d87** [comment]
Thanks, released the updated version
