### ISSUE TITLE
Proposal: ability to change health bar's color on specific conditions

### ISSUE THREAD

**Issue by PsHohe** [rgd87/Aptechka#110]
Great addon, recently tried it and I love it.

There are, however, a few things that would be awesome to have to be able to migrate from Grid2.

- Being able to change the health bar's color under a custom trigger (specific buff or specific health %).
- Being able to change the health bar's color depending on type of debuff (magic, poison, etc).
- Being able to establish a hierarchy for the conditions previously proposed.

**Comment by d87** [comment]
You can do all that except health %, assign things to healthColor widget
