### ISSUE TITLE
Lue error nil value

### ISSUE THREAD

**Issue by Meta-phaze** [rgd87/Aptechka#112]
I am getting a lua error on Sarkareth, possibly related to when raid members phase into the "downstairs"

![image](https://github.com/rgd87/Aptechka/assets/168177/38062279-d3b8-4c3a-a0e7-a089545ca6d2)

![image](https://github.com/rgd87/Aptechka/assets/168177/aebe0b7b-31d6-4dff-b4d4-462823991dea)

![image](https://github.com/rgd87/Aptechka/assets/168177/0ddfcfab-a02f-482f-b119-86e6dc287d9d)

It happens a lot on the fight and, I think, might be a recent issue.

**Comment by d87** [comment]
Well, that's something very strange, but i tried to fix it. Try 10.1.2

**Comment by Meta-phaze** [comment]
Thanks, next raid is next week, I'll let you know
