### ISSUE TITLE
Profile Auto-Switching not working because of GetTalentGroupRole giving wrong role type.

### ISSUE THREAD

**Issue by marknl** [rgd87/Aptechka#116]
Blizzard removed API call SetTalentGroupRole(). You cannot set your role via the little square icon within your talents window anymore.

GetTalentGroupRole (what Aptechka is using), is still usable, but not reliable anymore. It will return the value set from the old system. Which default to "DAMAGER" if none has even been set.

In my case I recently added dual spec to my priest and specced into Discipline on my 2nd spec, GetTalentGroupRole(2) will return "DAMAGER" because no role has ever been set and hence will fall back to the default value.

This hidden value that cannot be changed, will be your default "new" role when you are joining a party or raid.

From what I've seen, the only way right now to figure out what a player is specced into, is by counting the talentpoints used in each tab and derive a spec from that (most points used in).

There is also a UnitSetRole(), but haven't found a "get" variant for it.

**Comment by d87** [comment]
That's Wrath we're talking about, right?

**Comment by d87** [comment]
Right, they added LFD. Sorry but are these roles work in all groups like on retail or is it limited to LFD dungeons like in actual Wrath?

**Comment by d87** [comment]
Alright, in 10.2.0 update you can now select the role manually for the talent group like in Classic Era, In profile selection tab

**Comment by marknl** [comment]
Hey, yes we're talking about Wrath Classic.

First you had the squared icon on each of your talent windows where you could choose healer, dps, tank. This was bound to `SetTalentGroupRole()`. When LFD was released, those squares have been removed (and also the `SetTalentGroupRole()` function).

They introduced a new method of setting a role:
- Via LFD (before you queue up)
- When you're actually in a party or raid. You can then right click your unit frame, and see a submenu item called "Role" there you can change your role to Tank, Healer, Damage.

Both of these hace no influence on the return data `GetTalentGroupRole` will give. Hence making the auto profile switcher in the addon not work.

> Alright, in 10.2.0 update you can now select the role manually for the talent group like in Classic Era, In profile selection tab
Oh an update, nice, i'll have a look!

Do you think you'll get a working auto profile switcher working again for wrath classic, or will you stick with the manual switcher?

**Comment by d87** [comment]
Well it's still auto, you just have to tell it which of your specs are healers. And there's no other way to tell with old talent trees.
The group assigned role doesn't work because it only works in a group

**Comment by marknl** [comment]
I've tested the new feature, I'd consider this a good alternative to the fully automatic. Just have to set it once.
Thank you quickly resolving this issue, much appreciated! I'm a new user of this addon, i really like it! Thank you for all your effort!
