### ISSUE TITLE
When you are attacked by a monster

### ISSUE THREAD

**Issue by JSZMonkey** [rgd87/Aptechka#12]
Message: integer overflow attempting to store 3031385082
Time: Mon Sep 30 10:45:20 2019
Count: 2
Stack: integer overflow attempting to store 3031385082
[C]: in function `format'
...bs\LibClassicHealComm-1.0\LibClassicHealComm-1.0.lua:1727: in function `?'
...bs\LibClassicHealComm-1.0\LibClassicHealComm-1.0.lua:2073: in function <...bs\LibClassicHealComm-1.0\LibClassicHealComm-1.0.lua:2072>

Locals: (*temporary) = "DL::%d:%d:%d"
(*temporary) = 6064
(*temporary) = 3031385082
(*temporary) = 3031387882

**Comment by d87** [comment]
Should be fixed now in 1.13.15. If you have any other addons using HealComm it may still use the older version. But you probably don't
