### ISSUE TITLE
engravingInfo error on SoD when naked

### ISSUE THREAD

**Issue by zdeyn** [rgd87/Aptechka#121]
11x NugRunning/config.classic.lua:62: attempt to index local 'engravingInfo' (a nil value)
[string "@NugRunning/config.classic.lua"]:62: in function `isknowncheck'
[string "@NugRunning/NugRunning.lua"]:576: in function <NugRunning/NugRunning.lua:546>
[string "@NugRunning/NugRunning.lua"]:627: in function <NugRunning/NugRunning.lua:618>
[string "=(tail call)"]: ?

Locals:
INVSLOT_HAND = 10
engravingInfo = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'engravingInfo' (a nil value)"

I'm doing a naked, runeless hardcore run, and updating to 10.2.4 throws the above error whenever im in combat

**Comment by d87** [comment]
10.2.5 update will appear in a minute, thanks for reporting
