### ISSUE TITLE
Classic SOD Aura images no longer show

### ISSUE THREAD

**Issue by Prosperityz** [rgd87/Aptechka#124]
Auras use to show their icon. I have buffIcons where I put some buffs on one row. Then I made buffIcons2 to add other buffs on another row. All icons are not displaying. Including icon [BarIcon]

![image](https://github.com/user-attachments/assets/3e1ca5da-70e1-49df-8a85-5014c257fa56)

**Comment by d87** [comment]
Thanks, should be fixed in the 11.0.2 update
