### ISSUE TITLE
Custom Range check

### ISSUE THREAD

**Issue by stefan0uh** [rgd87/Aptechka#16]
Is it possible to add a custom range, for the in-range check?

Like on Classic all players use 40 yards, but as a mage, you want to check for 30 yards.

**Comment by d87** [comment]
Yeah, i don't have any up-to-date docs on advanced customization ready, so basically install this thing and put inside the spellID of your 30yd spell
[AptechkaUserConfig.zip](https://github.com/rgd87/Aptechka/files/4092298/AptechkaUserConfig.zip)

**Comment by d87** [comment]
Or wait, are mage buffs also 30yds? I should probably make that a default then

**Comment by stefan0uh** [comment]
nice, perfect! btw priest spells don't work on a mage I use this spell [Dampen Magic (30 yards)](https://classic.wowhead.com/spell=604/dampen-magic)

maybe check this library out [LibRangeCheck-2.0](https://www.wowace.com/projects/librangecheck-2-0), so you don't need it specifically for a class and the players can choose a custom range
