### ISSUE TITLE
raidframes to much space

### ISSUE THREAD

**Issue by chikoba** [rgd87/Aptechka#18]
hello,

since the last update my raidframes have to much space to each other, i cant get fix it or i find nothing in the settings to fix it.

![image](https://user-images.githubusercontent.com/50919618/73989545-6b99c780-4946-11ea-822a-482489687ab8.png)
![image](https://user-images.githubusercontent.com/50919618/73989569-82401e80-4946-11ea-862c-f6173cbb78a5.png)

**Comment by d87** [comment]
Unit gap and group gap settings change it, make sure you're editing the profile that is currently used if you don't see changes

**Comment by d87** [comment]
I found the bug now

**Comment by d87** [comment]
Fixed
