### ISSUE TITLE
Team display abnormal

### ISSUE THREAD

**Issue by 3735** [rgd87/Aptechka#23]
image link
 [http://wp.zsaxi.com/2020/03/3db0f3ec90a42723e2b50293e3da86b9.png](url)

I do n’t know why it is not highlighted because of distance。

Deleted the WTF folder  Still so

【WowClassic 1.13.4 33728】

**Comment by d87** [comment]
When this happens? Always when in a group? Only on a mage? It started happening after an update? 
Type /dump IsSpellInRange(GetSpellInfo(1459), "player")
Does it say 1?

**Comment by 3735** [comment]
not yet，
at first when lv 1-20 have this issues，lv60 not
result
lv 60 without issues
<img src="http://wp.zsaxi.com/2020/03/08e273b55c348e9cdb6d41facb2b68c6.png" />
lv 35 with issues
<img src="http://wp.zsaxi.com/2020/03/110eebf9f71b6e7fd6a35336b33d6d1a.png" />

**Comment by d87** [comment]
You pasted it wrong, remove spaces.

**Comment by 3735** [comment]
sorry ，
lv 35
<img src="http://wp.zsaxi.com/2020/03/9859e7b946bc76066cdbd54b5552f099.png" />

**Comment by d87** [comment]
Ok, now try /dump IsPlayerSpell(1459)

It seems the issue is that your 35 somehow doesn't have Arcane Intellect Rank 1 trained. I don't how that is possible

**Comment by 3735** [comment]
lv 35
<img src="http://wp.zsaxi.com/2020/03/49839af93411e3b081d1abe550a65675.png" />
lv 60
<img src="http://wp.zsaxi.com/2020/03/223fb3947779f0cc3d52ef4e64f7f6f9.png" />

**Comment by 3735** [comment]
now i  Learn  Arcane Intellect Rank 1，it is ok now
but when i lv1，how to show it

**Comment by 3735** [comment]
lv 35 just for item 12360 and item15846

**Comment by d87** [comment]
Arcane Intellect Rank 1 is available from lvl 1 and costs 10c. Most people will never notice this as it stops being an issue 3 minutes into the game, but mages need 30yd range change instead of universal 40 for decursing and buffing and that is the best option

**Comment by 3735** [comment]
Thanks, I know the solution, Aptechka is very good

**Comment by 3735** [comment]
Now I think, if a player does not learn the spell , there have a note

**Comment by d87** [comment]
Ok, i'll make it smart
