### ISSUE TITLE
Issue when Plater takes over Blizzard Name plates:

### ISSUE THREAD

**Issue by Kalandorno** [rgd87/Aptechka#25]
Message: Interface\AddOns\Aptechka\Aptechka.lua:435: attempt to call global 'CanAccessObject' (a nil value)
Time: Tue Jul 21 18:16:39 2020
Count: 2
Stack: Interface\AddOns\Aptechka\Aptechka.lua:435: attempt to call global 'CanAccessObject' (a nil value)
[string "@Interface\AddOns\Aptechka\Aptechka.lua"]:435: in function <Interface\AddOns\Aptechka\Aptechka.lua:434>
[string "=[C]"]: ?
[string "=[C]"]: in function `CreateFrame'
[string "@Interface\SharedXML\Pools.lua"]:113: in function `creationFunc'
[string "@Interface\SharedXML\Pools.lua"]:50: in function `Acquire'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:101: in function `AcquireUnitFrame'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:114: in function `OnNamePlateAdded'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:56: in function <...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:47>

Locals: self = <unnamed> {
 ignoreCUFNameRequirement = true
 WidgetContainer = <unnamed> {
 }
 ClassificationFrame = <unnamed> {
 }
 RaidTargetFrame = <unnamed> {
 }
 maxDispelDebuffs = 0
 disableMouse = true
 healthBar = <unnamed> {
 }
 BuffFrame = <unnamed> {
 }
 optionTable = <table> {
 }
 0 = <userdata>
 selectionHighlight = <unnamed> {
 }
 name = <unnamed> {
 }
 aggroHighlight = <unnamed> {
 }
 maxDebuffs = 0
 maxBuffs = 0
 LoseAggroAnim = <unnamed> {
 }
 castBar = <unnamed> {
 }
}
(*temporary) = nil
(*temporary) = <unnamed> {
 ignoreCUFNameRequirement = true
 WidgetContainer = <unnamed> {
 }
 ClassificationFrame = <unnamed> {
 }
 RaidTargetFrame = <unnamed> {
 }
 maxDispelDebuffs = 0
 disableMouse = true
 healthBar = <unnamed> {
 }
 BuffFrame = <unnamed> {
 }
 optionTable = <table> {
 }
 0 = <userdata>
 selectionHighlight = <unnamed> {
 }
 name = <unnamed> {
 }
 aggroHighlight = <unnamed> {
 }
 maxDebuffs = 0
 maxBuffs = 0
 LoseAggroAnim = <unnamed> {
 }
 castBar = <unnamed> {
 }
}
(*temporary) = "attempt to call global 'CanAccessObject' (a nil value)"

**Comment by Kalandorno** [comment]
THis is on Shadowlands Beta.

**Comment by d87** [comment]
I don't have beta to actually fix it.
But this should make it go away
/script Aptechka.db.global.hideBlizzRaid = false
/reload

**Comment by Kalandorno** [comment]
Do you want me to keep giving you any error messages i get?

**Comment by d87** [comment]
Sure, are there many? This one is really weird btw. Because i tested beta client in sandbox mode and at least in the build 35213 CanAccessObject function totally exists.

**Comment by Kalandorno** [comment]
Message: Interface\AddOns\Aptechka\Aptechka.lua:435: attempt to call global 'CanAccessObject' (a nil value)
Time: Tue Jul 21 19:09:23 2020
Count: 1
Stack: Interface\AddOns\Aptechka\Aptechka.lua:435: attempt to call global 'CanAccessObject' (a nil value)
[string "@Interface\AddOns\Aptechka\Aptechka.lua"]:435: in function `disableCompactRaidFrameUnitButton'
[string "@Interface\AddOns\Aptechka\Aptechka.lua"]:447: in function `?'
[string "@Interface\AddOns\Aptechka\Aptechka.lua"]:6: in function <Interface\AddOns\Aptechka\Aptechka.lua:5>

Locals: self = CompactRaidFrame1 {
 0 = <userdata>
 debuffFrames = <table> {
 }
 maxDispelDebuffs = 3
 inUse = true
 inVehicle = false
 background = CompactRaidFrame1Background {
 }
 powerBar = CompactRaidFrame1PowerBar {
 }
 hasDispelPoison = false
 healthBar = CompactRaidFrame1HealthBar {
 }
 overAbsorbGlow = CompactRaidFrame1OverAbsorbGlow {
 }
 hasDispelDisease = false
 horizTopBorder = CompactRaidFrame1HorizTopBorder {
 }
 vertRightBorder = CompactRaidFrame1VertRightBorder {
 }
 myHealPrediction = CompactRaidFrame1MyHealPrediction {
 }
 aggroHighlight = CompactRaidFrame1AggroHighlight {
 }
 myHealAbsorbRightShadow = CompactRaidFrame1MyHealAbsorbRightShadow {
 }
 overHealAbsorbGlow = CompactRaidFrame1OverHealAbsorbGlow {
 }
 newUnit = true
 hasDispelMagic = false
 hasDispelCurse = false
 selectionHighlight = CompactRaidFrame1SelectionHighlight {
 }
 myHealAbsorbLeftShadow = CompactRaidFrame1MyHealAbsorbLeftShadow {
 }
 totalAbsorbOverlay = CompactRaidFrame1TotalAbsorbOverlay {
 }
 unit = "player"
 unitExists = true
 displayedUnit = "player"
 unusedFunc = <function> defined @Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:46
 updateAllEvent = "GROUP_ROSTER_UPDATE"
 statusText = CompactRaidFrame1StatusText {
 }
 horizDivider = CompactRaidFrame1HorizDivider {
 }
 applyFunc = <function> defined @Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:324
 roleIcon = CompactRaidFrame1RoleIcon {
 }
 menu = <function> defined @Interface\FrameXML\CompactUnitFrame.lua:274
 optionTable = <table> {
 }
 otherHealPrediction = CompactRaidFrame1OtherHealPrediction {
 }
 dispelDebuffFrames = <table> {
 }
 buffFrames = <table> {
 }
 maxDebuffs = 3
 centerStatusIcon = CompactRaidFrame1CenterStatusIcon {
 }
 dropDown = CompactRaidFrame1DropDown {
 }
 myHealAbsorb = CompactRaidFrame1MyHealAbsorb {
 }
 maxBuffs = 3
 vertLeftBorder = CompactRaidFrame1VertLeftBorder {
 }
 horizBottomBorder = CompactRaidFrame1HorizBottomBorder {
 }
 name = CompactRaidFrame1Name {
 }
 readyCheckIcon = CompactRaidFrame1ReadyCheckIcon {
 }
 totalAbsorb = CompactRaidFrame1TotalAbsorb {
 }
}
(*temporary) = nil
(*temporary) = CompactRaidFrame1 {
 0 = <userdata>
 debuffFrames = <table> {
 }
 maxDispelDebuffs = 3
 inUse = true
 inVehicle = false
 background = CompactRaidFrame1Background {
 }
 powerBar = CompactRaidFrame1PowerBar {
 }
 hasDispelPoison = false
 healthBar = CompactRaidFrame1HealthBar {
 }
 overAbsorbGlow = CompactRaidFrame1OverAbsorbGlow {
 }
 hasDispelDisease = false
 horizTopBorder = CompactRaidFrame1HorizTopBorder {
 }
 vertRightBorder = CompactRaidFrame1VertRightBorder {
 }
 myHealPrediction = CompactRaidFrame1MyHealPrediction {
 }
 aggroHighlight = CompactRaidFrame1AggroHighlight {
 }
 myHealAbsorbRightShadow = CompactRaidFrame1MyHealAbsorbRightShadow {
 }
 overHealAbsorbGlow = CompactRaidFrame1OverHealAbsorbGlow {
 }
 newUnit = true
 hasDispelMagic = false
 hasDispelCurse = false
 selectionHighlight = CompactRaidFrame1SelectionHighlight {
 }
 myHealAbsorbLeftShadow = CompactRaidFrame1MyHealAbsorbLeftShadow {
 }
 totalAbsorbOverlay = CompactRaidFrame1TotalAbsorbOverlay {
 }
 unit = "player"
 unitExists = true
 displayedUnit = "player"
 unusedFunc = <function> defined @Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:46
 updateAllEvent = "GROUP_ROSTER_UPDATE"
 statusText = CompactRaidFrame1StatusText {
 }
 horizDivider = CompactR

**Comment by Kalandorno** [comment]
That is the only other error i have seen.

**Comment by Kalandorno** [comment]
However, the interface now doesnt even show up.

**Comment by Kalandorno** [comment]
Discord is Kalandorno#1783 if you want to chat differently
