### ISSUE TITLE
Addon stop working after reload

### ISSUE THREAD

**Issue by sonic1226** [rgd87/Aptechka#26]
After I reload the UI, addon just stops working (shadowlands beta). I can't even /apt gui to bring it up. The only solution I found is closing the game and reopening it. No error messages are shown too :/

**Comment by d87** [comment]
Try disabling "Hide blizzard raid frames" in global settings

**Comment by d87** [comment]
And btw are you sure you have errors enabled?
They could be disabled by default. /console scriptErrors 1

**Comment by sonic1226** [comment]
Got these errors:
--------------------------------------------
Message: Interface\AddOns\Aptechka\Aptechka.lua:435: attempt to call global 'CanAccessObject' (a nil value)
Time: Sun Jul 26 16:20:12 2020
Count: 20
Stack: Interface\AddOns\Aptechka\Aptechka.lua:435: attempt to call global 'CanAccessObject' (a nil value)
[string "@Interface\AddOns\Aptechka\Aptechka.lua"]:435: in function <Interface\AddOns\Aptechka\Aptechka.lua:434>
[string "=[C]"]: ?
[string "=[C]"]: in function `CreateFrame'
[string "@Interface\SharedXML\Pools.lua"]:113: in function `creationFunc'
[string "@Interface\SharedXML\Pools.lua"]:50: in function `Acquire'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:101: in function `AcquireUnitFrame'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:114: in function `OnNamePlateAdded'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:56: in function <...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:47>

Locals: self = <unnamed> {
 ignoreCUFNameRequirement = true
 WidgetContainer = <unnamed> {
 }
 ClassificationFrame = <unnamed> {
 }
 RaidTargetFrame = <unnamed> {
 }
 maxDispelDebuffs = 0
 disableMouse = true
 healthBar = <unnamed> {
 }
 BuffFrame = <unnamed> {
 }
 optionTable = <table> {
 }
 0 = <userdata>
 selectionHighlight = <unnamed> {
 }
 name = <unnamed> {
 }
 aggroHighlight = <unnamed> {
 }
 maxDebuffs = 0
 maxBuffs = 0
 LoseAggroAnim = <unnamed> {
 }
 castBar = <unnamed> {
 }
}
(*temporary) = nil
(*temporary) = <unnamed> {
 ignoreCUFNameRequirement = true
 WidgetContainer = <unnamed> {
 }
 ClassificationFrame = <unnamed> {
 }
 RaidTargetFrame = <unnamed> {
 }
 maxDispelDebuffs = 0
 disableMouse = true
 healthBar = <unnamed> {
 }
 BuffFrame = <unnamed> {
 }
 optionTable = <table> {
 }
 0 = <userdata>
 selectionHighlight = <unnamed> {
 }
 name = <unnamed> {
 }
 aggroHighlight = <unnamed> {
 }
 maxDebuffs = 0
 maxBuffs = 0
 LoseAggroAnim = <unnamed> {
 }
 castBar = <unnamed> {
 }
}
(*temporary) = "attempt to call global 'CanAccessObject' (a nil value)"


----------------------------------------------

Message: Interface\AddOns\Aptechka\Aptechka.lua:435: attempt to call global 'CanAccessObject' (a nil value)
Time: Sun Jul 26 16:20:12 2020
Count: 20
Stack: Interface\AddOns\Aptechka\Aptechka.lua:435: attempt to call global 'CanAccessObject' (a nil value)
[string "@Interface\AddOns\Aptechka\Aptechka.lua"]:435: in function <Interface\AddOns\Aptechka\Aptechka.lua:434>
[string "=[C]"]: ?
[string "=[C]"]: in function `CreateFrame'
[string "@Interface\SharedXML\Pools.lua"]:113: in function `creationFunc'
[string "@Interface\SharedXML\Pools.lua"]:50: in function `Acquire'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:101: in function `AcquireUnitFrame'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:114: in function `OnNamePlateAdded'
[string "@Interface\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua"]:56: in function <...e\AddOns\Blizzard_NamePlates\Blizzard_NamePlates.lua:47>

Locals: self = <unnamed> {
 ignoreCUFNameRequirement = true
 WidgetContainer = <unnamed> {
 }
 ClassificationFrame = <unnamed> {
 }
 RaidTargetFrame = <unnamed> {
 }
 maxDispelDebuffs = 0
 disableMouse = true
 healthBar = <unnamed> {
 }
 BuffFrame = <unnamed> {
 }
 optionTable = <table> {
 }
 0 = <userdata>
 selectionHighlight = <unnamed> {
 }
 name = <unnamed> {
 }
 aggroHighlight = <unnamed> {
 }
 maxDebuffs = 0
 maxBuffs = 0
 LoseAggroAnim = <unnamed> {
 }
 castBar = <unnamed> {
 }
}
(*temporary) = nil
(*temporary) = <unnamed> {
 ignoreCUFNameRequirement = true
 WidgetContainer = <unnamed> {
 }
 ClassificationFrame = <unnamed> {
 }
 RaidTargetFrame = <unnamed> {
 }
 maxDispelDebuffs = 0
 disableMouse = true
 healthBar = <unnamed> {
 }
 BuffFrame = <unnamed> {
 }
 optionTable = <table> {
 }
 0 = <userdata>
 selectionHighlight = <unnamed> {
 }
 name = <unnamed> {
 }
 aggroHighlight = <unnamed> {
 }
 maxDebuffs = 0
 maxBuffs = 0
 LoseAggroAnim = <unnamed> {
 }
 castBar = <unnamed> {
 }
}
(*temporary) = "attempt to call global 'CanAccessObject' (a nil value)"

**Comment by d87** [comment]
Yup, disabling "Hide blizzard raid frames" will help with that

**Comment by sonic1226** [comment]
IS it on Interface -> Raid profiles? Not finding that option

**Comment by d87** [comment]
Interface > Addons > aptechka > global settings

**Comment by sonic1226** [comment]
Nice! Seems to be working giving no errors now :) Tnx!

**Comment by sonic1226** [comment]
Anyway I can increase the number of BUFFS that are shown? I'm using bars on all my buffs but it seems to be capped at 5. Also any way to move the buff indicators to custom spots on the frame? or are they set in certain places (like buff1 buff2 and so on) ?

**Comment by d87** [comment]
Well there's a problem with that level of customization currently.
If you're familiar with some wow Lua what you can do is install this https://github.com/rgd87/AptechkaUserConfig/releases/download/1.0/AptechkaUserConfig_1.zip

And there you can create new indicators or move the existing ones. Although increasing "bars" to more than 5 i don't think is possible

**Comment by d87** [comment]
https://github.com/rgd87/Aptechka/releases
Latest build allows creating custom bar and icon groups, and default bars group can go up to 7 now
