### ISSUE TITLE
Removing a spell from widget not working while spell/buff is active

### ISSUE THREAD

**Issue by spamwax** [rgd87/Aptechka#32]
If I add a buff to a widget and apply the buff to the unit, it correctly appears in it.
However if I remove the buff from widget while the buff still active, does not remove the buff from UI and keeps it until buff is dropped.
Additionally when buff is dropped, the background of widgets remains visible. For example if Glimmer of Light is added to an indicator and immediately removed from it, after buff is expired the background of widget box remains visible covering other widgets in that location.
Ex:
Top left corner is in normal state. Glimmer of Light is added to "raidbuff[BarArray]" widget (top left corner box)
<img width="284" alt="p1" src="https://user-images.githubusercontent.com/1251233/92989529-ec9fdb00-f4a2-11ea-93f2-796fa4c32297.PNG">

This is when Glimmer is applied and then its spell is removed from the above mentioned widget while buff is still active. I think the expected behavior is that the buff should disappear since it's not part of the widget but it still showing here!
<img width="228" alt="p2" src="https://user-images.githubusercontent.com/1251233/92989531-f0336200-f4a2-11ea-8e44-c48101dd005f.PNG">

After last step and when the buff runs out, the background of buff/widget is still visible (covering the L letter from first picture). Same thing can be seen on the lower right long bar, is this intended behavior?
<img width="240" alt="p3" src="https://user-images.githubusercontent.com/1251233/92989536-f3c6e900-f4a2-11ea-9375-bdcc0f4e2127.PNG">

Same issue happens with other widgets, following picture is after I added and removed Glimmer from center icon and now it's stuck in the middle of frame. Only a '/reload' fixes the issue.
<img width="228" alt="p4" src="https://user-images.githubusercontent.com/1251233/92989732-62587680-f4a4-11ea-9497-8ac025a6b1c2.PNG">

**Comment by d87** [comment]
Fixed
