### ISSUE TITLE
Request: Add a builtin debuff "type" that can be assigned to widgets

### ISSUE THREAD

**Issue by spamwax** [rgd87/Aptechka#33]
There are 4 debuff types (magic, disease, curse, poison) that each healer can only dispel some of them.
Having a debuff type in spell list for all of above lets each healer class only assign them to widget so it can be easily identified for dispelling. Right now, I not only need to know all possible spell names for such auras but should also individually customize their profile to just show the ones I can dispel

**Comment by d87** [comment]
Why are you manually adding debuffs to spell list?
It already shows all the debuffs a unit has in debuff icons, and there's a DispelStatus thing that lights up when unit has something dispellable.

**Comment by spamwax** [comment]
Thanks for quick response. I didn't notice it in Status List.
While testing, I ran into another issue.
Click Status List, click DispelStatus, now try to change the "Assign to" to something else than default. Upon closing the drop-down menu the default setting is always added back to the list. is this intended?

**Comment by d87** [comment]
No, that's a bug

**Comment by spamwax** [comment]
ok, thanks.
Is it possible to save the size/orientation of frames in a profile? right now it seems they are global settings.
Essentially I want to have a different size units in a 5-man vs a raid.

**Comment by d87** [comment]
It is saved per profile. everything that's in profile settings is.
Fixed the status list bug too

**Comment by spamwax** [comment]
great and thanks. I will report back on dispelables on different healers when I can find a group on ptr and test it.
other issues seems to be fixed.
