### ISSUE TITLE
Feature Request: Testing Group Layouts & Size

### ISSUE THREAD

**Issue by spamwax** [rgd87/Aptechka#36]
I tested this in a beta 5-man and I think having a way of testing the layout, size and direction of groups would be very nice.
Something that shows couple of dummy health bars so some of the more general settings (such as size, orientation, location in screen) can be tested without a full group.
Feel free to close this if you don't think it's worth the time/effort to implement this.

**Comment by d87** [comment]
Alright, done in beta43.

**Comment by spamwax** [comment]
Great, thanks for quick update.
How does the Blacklist spells work with widgets? For example I see Forebearance in Blacklist but then it is also assigned to a bar under Spells and shows up there! What's the intended usage/application of Blacklist then?

**Comment by d87** [comment]
It's for debuff icons.

**Comment by spamwax** [comment]
debuff icons is the widget that shows automatic boss/raid debuff?
Also there is ! mark next to Widgets and Blacklist, what does that mean?
Is there a way of listing what Spells are assigned to a specific widget or vice versa without going through list of all spells and manually inspecting them?

**Comment by d87** [comment]
It shows all debuffs
! means relatively new
No way

**Comment by spamwax** [comment]
ok, thanks.
1. So how do I do an icon that only does specific/important raid debuffs? For example in Nzoth fight everyone gets [Infinity' Toll](https://www.wowhead.com/spell=319346/infinitys-toll) as a debuff and as a healer I don't want to see that on all unit frames. But then I want to see some other important buffs. Do I have to create a separate widget and manually assign the spells to it?

2. Other issue I ran into is related to health colors which seems to be private and cannot be created/modified. On healer spec I assigned paladin's Beacon of Light to the color so it will change it if a unit doesn't have it. But when I switch to tank/dps, obviously I don't want to see the color change. So I thought I should make the color widget private to healing profile but as you know it's not listed there. Any suggestions?

**Comment by d87** [comment]
1. Use blacklist for what you don't want to see. And use debuff highlights for when you really want to see some debuff
2. Health color is literally a health bar color, there's nothing more to create. My suggestion is to only use missing flag for raidwide buffs like PWF. Otherwise you (or me) can go crazy filtering out the million possible reasons why a spell can be missing. Use weakauras for that

**Comment by spamwax** [comment]
Ok, thanks for clarifications and thanks for answering my questions, appreciate it. Hopefully I can write a basic guide soon so all this information is gathered in one place.
Since there is no profile export/sharing feature yet, which folder in WTF I should look for if I want to copy my current settings from beta to retail?

**Comment by d87** [comment]
WTF\Account\<AccName>\SavedVariables\Aptechka.lua

But install this first if you want to use it on retail https://github.com/rgd87/Aptechka/releases/download/8.3.SL-beta4/Aptechka-8.3.SL-beta4.zip

**Comment by spamwax** [comment]
on 9.0.14-beta2, the layout test only shows 5 members, it used to do show all 40 frames, is this intentional?

<img width="266" alt="Wow_2020-11-19_0056" src="https://user-images.githubusercontent.com/1251233/99669026-7ab4b680-2a3c-11eb-8331-88b4a7274c1e.png">

**Comment by d87** [comment]
press it more, it shows different group sizes now
