### ISSUE TITLE
DispellStatus not showing or showing as dark square

### ISSUE THREAD

**Issue by spamwax** [rgd87/Aptechka#37]
I tested assigning the DispelStatus to Icon & IconArray.
For Icon, the debuff shows up on frame as a dark square only
[Short Video - Dark Icon](https://streamable.com/ol5wwf)

For IconArray nothing shows up at all
[Short Video - Missing Icon](https://streamable.com/4oof5k)

Now if I assign another spell to IconArray (say beacon), that spell shows up correctly, which also causes  the debuff shows up as  but it actually uses the icon for the beacon!

[Short Video - Wrong Icon](https://streamable.com/od7wv1)

**Comment by spamwax** [comment]
Updated the report with a third video showing wrong icon

**Comment by d87** [comment]
Dispel only carries the info that some debuff type is present, without any details about the dispellable auras itself
Icons don't know how to display it. It sure is an issue, but for icons i can at best select some spell icons representing different debuff types

**Comment by spamwax** [comment]
do you mean like the school of debuff (magic, poison...)? that would be more helpful than seeing an empty icon
I think in Grid2, I can assign the debuff's school (magic, disease, magic for Paladin for ex) to an icon widget and it shows up with the correct icon display, I wonder how they do that

**Comment by spamwax** [comment]
I think for now I am going to create a bigger square indicator in the center of frame to quickly know who to dispel.
But as you said it's kind of an issue as sometimes you really don't wanna dispel, say a poison, and save the cooldown for a more important one.

**Comment by d87** [comment]
Honestly this whole idea of smashing dispel as you see a thing light up is not relevant in modern wow.
Trying to only see dispellable debuffs is also a bad idea.
I didn't even want to add this feature at first, because people probably know what they can and should dispel.
But I guess it's useful on alts and for dps specs

**Comment by spamwax** [comment]
agreed, as I said it's not smashing but more of tracking what's going on in a more clear way. in one of the SL dungeons I think a dispelable debuff can stack up to a certain point after which it becomes a fatal debuff.
Another example  I can think of is the Ilgynoth fight where you want to dispel it at a certain time.

**Comment by d87** [comment]
Latest release supports dispel types on Icon and Texture widgets,

**Comment by spamwax** [comment]
Is this backported to retail version? (since last time you asked me to use a specific release on retail)

**Comment by d87** [comment]
It is in 8.3.SL-beta7
