### ISSUE TITLE
Player name issue

### ISSUE THREAD

**Issue by spamwax** [rgd87/Aptechka#40]
I am not really sure if this is Aptechka's issue since all groups I joined through dungeon finder worked OK.
However the screenshot shows the name duplication when the group was formed outside of LFG for an m+ key.

<img width="301" alt="p11" src="https://user-images.githubusercontent.com/1251233/94328538-65159a00-ff81-11ea-869e-80fd881d09e9.PNG">

**Comment by d87** [comment]
Thanks, fixed. That was a bug with the latest version
