### ISSUE TITLE
State of "Profile-Specific" check box is not saved

### ISSUE THREAD

**Issue by spamwax** [rgd87/Aptechka#43]
This happens on a widget that I create on, say, `Profile 1`.
If I create a new profile and copy `Profile 1` onto it, toggling the check box doesn't seem to be saved (clicking around or closing/opening of the option window resets the check box back to its state from `Profile 1`)

**Comment by spamwax** [comment]
It seems the updating issues also affects all the settings of the widget as well.
For example, the X offset of a widget in `Profile 1` and `Profile 2` (copied version) shows the same value even though switching between profiles correctly shows the widget in different locations, implying that offset is working and it's just not getting displayed correctly in the option window.

[Video of widget](https://streamable.com/22uo9f) offset working in different profiles but the number staying the same:

**Comment by d87** [comment]
Thanks, fixed in beta51

**Comment by spamwax** [comment]
Thanks for quick fix, I will try it soon.
I also ran into similar issue where I can create a widget but when I want to assign a spell to it it does not show up in the list!
However a `/reload` fixes it and widget gets displayed for the spelli

**Comment by d87** [comment]
Just re-selecting the spell should be enough to update the list. Idk, it's a minor issue that is hard to fix. In spell forms there may be unsaved data that you can't just discard too.
