### ISSUE TITLE
Indicator flashing temporarily

### ISSUE THREAD

**Issue by spamwax** [rgd87/Aptechka#44]
When I assign Rejuvenation to an indicator, for the first couple of seconds the square [keeps flashing](https://streamable.com/tiktue) and then it stops & show regular progress! Is this intended behavior?

**Comment by d87** [comment]
I was testing animation and then i forgot to remove that from rejuv. Fixed

**Comment by spamwax** [comment]
ok, thanks.
Also for the entire dungeon run this druid was stuck with a debuff icon:
![World of Warcraft 10_2_2020 12_17_26 AM (2)](https://user-images.githubusercontent.com/1251233/94889126-21bb9f80-0449-11eb-8e8a-2fbdabe22cbd.png)

Not sure if it was a legit debuff but unlikely he only had it all the time. Maybe I am missing something

**Comment by d87** [comment]
Probably some bullshit cooldown debuff from shadowlands. I haven't seriously played beta to blacklist these things
