### ISSUE TITLE
Widgets don't show progress/time if the assigned spell is not casted by player

### ISSUE THREAD

**Issue by spamwax** [rgd87/Aptechka#45]
I added multiple widgets (text, icon, progress icon,...) to test this.
Then I created a new spell for tracking combat pots (307162 Potion of Spectral Intellect) and assigned all the above widgets to this spell. If the "Casted by Player" checkbox is not selected in the spell window, none of the widgets shows the progress of spell/buff and they are all static icons/widgets.

**Comment by d87** [comment]
Have you turned on "Show Duration" tho?

**Comment by d87** [comment]
I checked and everything seems to be fine

**Comment by spamwax** [comment]
yes I had added that. However it seems it is now showing the progress without that checkbox!
The only thing I did that fixed the issue was an `/apt purge` command I used after opening this ticket! I was playing with options to fix this and toggled couple of setting so it may have caused the glitch.

**Comment by spamwax** [comment]
Can you please also check and see the dispellstatus can show the progress of the debuff?
I am assigning the dispellstatus to an icon and it only shows a generic icon for the type of debuff. It also does not show any indication of the progress of the debuff, just a fixed icon. @d87
