### ISSUE TITLE
Feature request: Auto switching of profile based on class and role/raid size

### ISSUE THREAD

**Issue by spamwax** [rgd87/Aptechka#48]
This is a nice to have feature if it can be implemented down the road.

I'd like to be able to have a healer profile for a paladin vs a druid. Reason behind this is that my paladin's WA to track spells that's close to my character does not take as much space as the WAs for a druid. So it would be nice to automatically switch the profile based on class. 
Maybe add a parent drop-down menu for class within which we have access to current selection of auto-switching based on role & group size

**Comment by d87** [comment]
That's too much for gui, but now you can use this hook to select whatever
https://github.com/rgd87/AptechkaUserConfig/commit/145a82243d3463f8945290f3a65b60c830fb93b4

**Comment by spamwax** [comment]
would I call this from, say, WeakAuras? or console/command line?
Can you provide an example of how to call this function & what it's supposed to return?

**Comment by d87** [comment]
You can either download that AptechkaUserConfig repo and install it as a separate addon (the safest option)
or use https://www.wowinterface.com/downloads/info24734-REHack-UINotebook.html and put it there
WeakAura also probably can work. but i don't know the details.
Anywhere as long as it executes after Aptechka is loaded, and ideally before PLAYER_LOGIN

And you don't literally call it, you just define it and if it's defined then it overrides the normal profile switching logic with whatever you put in there. Returns the profile name it should switch to
```lua
Aptechka.ProfileLogicFunc = function(autoProfile, role, class, groupType, numMembers)
    if role == "HEALER" and numMembers < 5 then
        return "5man"
    else
        return "Default"
    end
end
```

**Comment by spamwax** [comment]
Nice!
The setting from the `userconfig.lua` of AptechkaUserConfig override the settings that use has defined through GUI?
For example I see `config.TargetStatus` table defined there, if I change target status in GUI too which one has priority?

**Comment by d87** [comment]
What it's doing is essentially modifying default config (config.lua file) before it's loaded.
And then GUI settings are layered on top of that.

btw this is not really something people should use normally. Unless you understand what you're doing you can actually break stuff here.
So I'm not advertising it

**Comment by spamwax** [comment]
numMembers is the current players in the group or is it the group size?

**Comment by d87** [comment]
current
