### ISSUE TITLE
Show progress of "Dispell" status

### ISSUE THREAD

**Issue by spamwax** [rgd87/Aptechka#49]
I am not sure if this is possible and I know you said Blizzard's API for dispellable is limited.

Right now if I assign Dispell status to an icon, it only shows a static generic icon.
In a dungeon run today multiple group members had a dispellable debuff on them. I'd like to be able to see which debuff has the longest duration left so I can dispel that person and not waste the dispel CD on a player whose debuff is about to fall off.

**Comment by d87** [comment]
I don't understand what's wrong with just using debuff icons. It's not even like there are multiple debuffs at a time that often so you can't find what you need, and even if there were multiple, the dispellable ones are prioritized to be first in the list.
I suppose I can make dispel status carry debuff info, but what if there is more than 1 dispellable debuff? Are you going to ask to show all of them? And then I'd just be reinventing debuff icons when they are already there showing everything

**Comment by spamwax** [comment]
The reason I'd like to see separate debuff groups based on dispell status are:
- Majority of time debuffs on players are not dispellable and for most of them I really need to pay attention to as a healer. So bundling those with the ones that I have to pay attention and possibly dispell is the issue in my opinion.  I guess I'd like to have a large icon in the middle of frame to draw my attention for dispelling, rather than looking at a group of icons in the corner of frame constantly constantly to see if there is dispell debuff there.
- In boss fights, the debufficons group will show boss's debuff with a bigger scaling (if I am not mistaking), as you know most of them are not dispellable. So if dispell status is part of that group now I have to quickly decide if the unit is dispellable based on the scale of icon (is it boss debuff or is it something i can dispel)
- I definitely don't want you to reinvent stuff, and I personally will not ask for showing more than one dispell debuff :) but I understand your concern. Is it possible to assign the dispell status to a groupIcon?
- I guess I can follow what you are suggesting and use the debufficon group and use the max scaling for dispellable icons

**Comment by d87** [comment]
I added it, but still... I think all debuffs are equally important, dispellable or not. Trying to go against them because Grid does or whatever is not good. Original Grid was getting away with it because it's fine for vanilla level mechanics, but then it increasingly became a problem. How it is Grid2 i don't even know, but I myself added debuff icons in like mop and would never go back

**Comment by spamwax** [comment]
Thanks for adding this, really appreciate it.
I couldn't play MoP, can you please provide a little info on how the debuffs were back then?

Using beta55, I now see the a texture (along with an `!` animation) whenever a dispellable debuff is applied.
I couldn't turn the texture off even if I assign nothing to "Dispel" under "Status List", is this intended?

Grid2 has a dispellable status that can be assigned to icons (and maybe other widgets, not sure).

**Comment by d87** [comment]
Uhh, no you should be able to deselect this texture. The issue is probably that both DispelStatus and DebuffAlert1 and 2 use the same texture.  So you should deselect it on both.

It's not like mop had special debuffs, i'm just saying that by around that time due to increasing number of mechanics i felt hiding debuffs became a noticeable problem. Before that I too was just doing things the grid way

**Comment by spamwax** [comment]
oh yea, I forgot that I had added the poison debuff of a trash mob to "Debuff Highlighting" to test my settings.

I agree keeping track of all debuff and hiding them is not easy. That wasn't my intention, I just wanted to have a better heads-up for stuff that I can dispel.

So to understand how the current mechanisms of debuff in Aptechka is working:
- All debuff (boss or non-boss) are shown in the `debuffIcons` widget unless they are explicitly blacklisted
- If a debuff is dispellable, it will also show up on other widgets that are listed under "Dispel"
- The scaling slider under Dispel is only applied to `debuffIcons` widget (and not the one under Dispel status"

Is this kinda of accurate?

**Comment by d87** [comment]
No the scale part is wrong, it has nothing to do with debuffIcons, it's the scale of DebuffStatus itself. For example in default config LOSStatus and heal traces use the same widget, But LOS has 2x scale on it so appears a lot bigger.

On debuffIcons there's a separate slider that only controls boss auras big vs normal sized ones

**Comment by spamwax** [comment]
LOS=line of sight?
I haven't seen it in any of default of configs

**Comment by spamwax** [comment]
ok, so if I assign the bigger scale to Dispel under Status List, then that scale is applied to any widget that may be used to show the dispellable debuff?

**Comment by d87** [comment]
Yeah, at least Bars, Indicators and Textures. Gotta check if icons do it too

**Comment by d87** [comment]
They don't, and i guess it's better stay that way with icons, having randomly scaled will cause more harm than good
