### ISSUE TITLE
Adding customization to built-in status

### ISSUE THREAD

**Issue by spamwax** [rgd87/Aptechka#52]
- My most favorite feature of Aptechka is the incomingCastIcon which helps a lot in M+. Right now there is now way to assign that status to any other widget like a bar or `pixelGlow` widget. Is it possible to add this? Adding this lets the user to create a white list of important spells in M+ so proper decisions can be taken in terms of applying external damage reduction like Ironbark or Blessing of Protection
- Similarly couple of other key features like `mitigation` are not customizable (currently assigned to a `bar`) I know I can find all mitigations in spell list and assign them to an icon but since Aptechka has a mechanism to capture them, wouldn't it be better to let the user assign it to different widgets/icon?
- Another example is the customization of heal/damage absorbs (let user change color/texture?)

**Comment by d87** [comment]
1. I've added IncomingCastStatus to config in 9.0.6, but not to GUI yet. if you reassign it to icon and a bar you'll get a proper castbar.
Regarding cast highlights not sure when and how, but yeah, it'd be nice. Like always, GUI is the problem here.
Actually, when i first added incoming casts i had an option to only show casts from the whitelist, but it quickly became clear that just showing everything is always better.
I still maintain the list tho, it's used to show casts with any degree of importance on top of other garbage.
https://github.com/rgd87/Aptechka/blob/5d453c84422119dfb56e7a9bd7eaa1c01cbf5048/config.lua#L687

2. What mechanism to capture? ```mitigation``` is just a default bar widget. I guess what you mean is mass reassigning stuff that's using the same template. Yeah, that's a problem.

3. What's wrong with default heal and absorb? I don't want to do this because there's an option to invert healthbar colors (which in fact most people use weirdly) and heal/absorb colors are configured differently based on that. If I make them customizable i can't control that anymore, without overwriting user settings.
But you can customize them in AptechkaUserConfig. So if you're the sort of person that's going around with their own absorb textures, then maybe you can manage to do it in Lua.

Also in 9.0.6 i've added a floating icon thing, it shows events like potions, healthstone, damage cooldowns. For now, it's disabled by default in all profiles. It's kind of a test run of it, and it could be annoying in raids.

**Comment by spamwax** [comment]
1. What's the command line to reassign it? or what should I change in UserConfig?
2. I think I wasn't clear enough. Right now when a tank uses mitigation I see bars at the bottom of the frame. So it seems Aptechka already knows about the mitigation spells without me specifying them. So I was wondering if the `mitigation` which is currently a bar in widget lists can be changed to icon.
3. I don't have a way of testing the absorbs colors/texture, but remembering from very few times they were active in dungeons I couldn't easily tell/remember which one is heal absorb and which one is damage absorb. That's why I want to be able to change them somehow.
On a separate but related note, I think I found a bug with _invert health color_. I'll open a separate issue.

**Comment by d87** [comment]
```lua
config.IncomingCastStatus.assignto = set("incomingCastIcon", "bar4")
```
No, default widgets can't be deleted or replaced.

**Comment by d87** [comment]
In 9.0.7 you can use this to do what you wanted.
```lua
config.templates["ActiveMitigation"].assignto = set("icon")
```
Runic power is it's own thing tho, not using AM template

**Comment by spamwax** [comment]
That's great, thank you 👍 
How do I deactivate the default/builtin IncomingCastStatus  if I've assigned it to something else using `config.IncomingCastStatus.assignto` option? The only way I thought of was to set the alpha of current incomingcast widget to 0!

**Comment by d87** [comment]
Uhh... are you actually having problems with it?
You shouldn't need to deactivate anything.
1) When you use userconfig you're effectively modifying the default settings.
2) In most cases widgets aren't created until they're used. So if nothing is assigned to _incomingCastIcon_ then it's not even there

**Comment by spamwax** [comment]
I used `config.IncomingCastStatus.assignto = set("incomingCastIcon", "bar4")` as you suggested (I am assigning it to a diff widget that bar4) and restarted the game.

But `incomingCastIcon` widget shows up in the list, and since it's not green I am assuming it's added by the mod?
<img width="173" alt="temp1" src="https://user-images.githubusercontent.com/1251233/97104566-3cb9b200-168b-11eb-96f0-dc4a9d0debb4.PNG">

Should I delete that?

**Comment by d87** [comment]
That list is just widget settings. And if incomingCastIcon was still being used then it'd be created from these settings.

**Comment by spamwax** [comment]
ok, understood. But using the custom config doesn't turn it off. I could see two widgets showing the incoming cast at the same time!

**Comment by spamwax** [comment]
![ezgif com-video-to-gif(4)](https://user-images.githubusercontent.com/1251233/97104947-f9ad0e00-168d-11eb-9e0d-4824fd721e88.gif)

**Comment by d87** [comment]
Type ```/dump AptechkaDefaultConfig.IncomingCastStatus```
What does it say?
And what do you have in your UserConfig? It should be just ```config.IncomingCastStatus.assignto = set("customIcon", "customBar")```

**Comment by spamwax** [comment]
UserConfig has most of stuff that it came with after I downloaded the addon. But I added some profile logic change and `incomingCastStatus` as well as `ActiveMitigation`. This is my current [userconfig.lua](https://gist.github.com/spamwax/a346b6aceb02d8bb25f4798ab9c5eaed)

<img width="383" alt="temp1" src="https://user-images.githubusercontent.com/1251233/97105438-0da63f00-1691-11eb-9c29-0a1acef2f640.PNG">

**Comment by d87** [comment]
It should be just ```config.IncomingCastStatus.assignto = set("Glimmer")```

**Comment by spamwax** [comment]
I see the issue now! I thought first argument of `set("incomingCastIcon", "Glimmer")` is the name of status! My bad :)

**Comment by spamwax** [comment]
What's the new floatingicon widget for?

**Comment by d87** [comment]
>Also in 9.0.6 i've added a floating icon thing, it shows events like potions, healthstone, damage cooldowns. For now it's disabled by default in all profiles. It's kind of a test run of it, and it could be annoying in raids.

Enable  Aptechka > Profile Settings > Buff Gain Floating icon
And then you'll see it

**Comment by d87** [comment]
First version with GUI for templates: https://github.com/rgd87/Aptechka/releases/tag/9.0.10-beta1

**Comment by spamwax** [comment]
I'll try it as soon as I can get my damn M.2 drive to boot :)
By the release notes, I am guessing it's a better way of organizing user customizations, right?

**Comment by d87** [comment]
Well it's like doing ```config.templates["ActiveMitigation"].assignto = set("icon")``` but GUI.

**Comment by spamwax** [comment]
hmm... I guess I am not familiar with the concept of templates in Aptechka then. So `config.templates["ActiveMitigation"].assignto = set("icon")` causes all my characters see the same assignment?

**Comment by d87** [comment]
In short if you reassign template to different widgets all the spells that use it will follow. So you don't have to individually reassign 70 different cooldowns

**Comment by spamwax** [comment]
oh, I see, that's pretty neat.

**Comment by spamwax** [comment]
After clicking save to create a user template

```lua
2x SharedXML\TableUtil.lua:111: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: in function `pairs'
[string "@SharedXML\TableUtil.lua"]:111: in function `CopyTable'
[string "@Aptechka\Options\SpellList.lua"]:251: in function <Aptechka\Options\SpellList.lua:207>
[string "=[C]"]: ?
[string "@Ace3\AceGUI-3.0\AceGUI-3.0-41.lua"]:72: in function <Ace3\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@Ace3\AceGUI-3.0\AceGUI-3.0-41.lua"]:306: in function `Fire'
[string "@Ace3\AceGUI-3.0-41\widgets\AceGUIWidget-Button.lua"]:22: in function <...dOns\Ace3\AceGUI-3.0\widgets\AceGUIWidget-Button.lua:19>
```

**Comment by d87** [comment]
Fixed here https://github.com/rgd87/Aptechka/releases/tag/9.0.10-beta3

**Comment by spamwax** [comment]
I should not read your release notes as they bring more questions to mind about Aptechka's features :)

**Comment by spamwax** [comment]
ok I see how it works.
So now I can assign multiple spells to a template to group them up, and later if modify the template's "assigned to" widget all of the spells will be updated.
As in before, I had to

1- Either manually change the widgets for all those spells
2- Or if I was lucky and only wanted to change location/size (and not type/icon/bar/text) of them I'd just update that particular widget's properties

**Comment by d87** [comment]
Yeah, that's the idea.

**Comment by spamwax** [comment]
is it possible to add the new flyout animation (or the flashing animation) to buffs/debuffs that are about to expire?

**Comment by d87** [comment]
Later maybe another floating icon for when buffs actually expire. That was the plan at first but there's like no space left for it in the default setup.
But flashing when icons are about to expire would be kinda disproportionally costly for performance, so i don't want to do that.

**Comment by spamwax** [comment]
how about changing the color of bars/squares at a set time?

**Comment by d87** [comment]
I'll try it

**Comment by d87** [comment]
https://github.com/rgd87/Aptechka/releases

In the latest beta there's a new widget type BarIcon and it replaces the old default center icon and buffIcons.
It also plays animation when you can refresh

**Comment by spamwax** [comment]
Looks good!

Regarding templates:
Each spell/buff has now a template assignment as well as a "assign to" option! Which one takes priority? Shouldn't "assign to" become disabled if user has select any template (other than None) from the drop down menu?

**Comment by d87** [comment]
spell settings only inherit templates, you can layer individual spell settings on top

**Comment by spamwax** [comment]
so if the chosen template is using a bar my "assign to" is using another widget, say, icon then the icon will take precedence?

**Comment by d87** [comment]
yes

**Comment by spamwax** [comment]
under debuffIcons, there is "Boss Scale". I have noticed that debuffs from dungeon bosses don't honor that setting so the stay in default size of the widget. Is that scale only for raid bosses?

**Comment by d87** [comment]
What debuffs use it or not is detemined by blizzard and it's usually reserved for something important, not just anything.  I also have a table with spell Ids that flag it in addition to that, but that's mostly for pvp CC debuffs.

**Comment by d87** [comment]
For questions now you can use https://github.com/rgd87/Aptechka/discussions
Or ask in discord
