### ISSUE TITLE
LUA Error when adding new spells

### ISSUE THREAD

**Issue by spamwax** [rgd87/Aptechka#54]
I am on 9.0.7. And when I try to create an Aura in Spell List I get the following error after entering the spell id and clicking save. (I tried with multiple spell ids 1044, 297412, 54149 for holy paladin)

```lua
2x SharedXML\TableUtil.lua:111: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: in function `pairs'
[string "@SharedXML\TableUtil.lua"]:111: in function `CopyTable'
[string "@Aptechka\Options\SpellList.lua"]:210: in function <Aptechka\Options\SpellList.lua:179>
[string "=[C]"]: ?
[string "@Ace3\AceGUI-3.0\AceGUI-3.0-41.lua"]:72: in function <Ace3\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@Ace3\AceGUI-3.0\AceGUI-3.0-41.lua"]:306: in function `Fire'
[string "@Ace3\AceGUI-3.0-41\widgets\AceGUIWidget-Button.lua"]:22: in function <...dOns\Ace3\AceGUI-3.0\widgets\AceGUIWidget-Button.lua:19>
```

And when I use an spell id that is already in the list, it overwrites my modifications to that table and restores it to default widget (not sure if this is related to lua error or it's intended behavior.)

**Comment by d87** [comment]
Fixed the error in 9.0.8
