### ISSUE TITLE
Lua error

### ISSUE THREAD

**Issue by Haagen-Dazs** [rgd87/Aptechka#6]
1x [ADDON_ACTION_BLOCKED] AddOn 'Aptechka' tried to call the protected function 'NugRaid1UnitButton3:SetFrameStrata()'.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: in function `SetFrameStrata'
Aptechka\frame.lua:1009: in function `?'
Aptechka\Aptechka-8.0.10.lua:1580: in function `SetupFrame'
[string "*:OnLoad"]:1: in function <[string "*:OnLoad"]:1>
[C]: in function `CreateFrame'
FrameXML\SecureGroupHeaders.lua:164: in function <FrameXML\SecureGroupHeaders.lua:123>
FrameXML\SecureGroupHeaders.lua:488: in function `SecureGroupHeader_Update'
FrameXML\SecureGroupHeaders.lua:62: in function <FrameXML\SecureGroupHeaders.lua:60>

Locals:
InCombatSkipped

**Comment by d87** [comment]
ok, thanks, fixed in https://github.com/rgd87/Aptechka/commit/95c2a25c69b1922cf0b0cf6e5cef219c5bc1e111
Did you encounter that often?

**Comment by Haagen-Dazs** [comment]
Since I started using this addon today, I got 2 errors in like 2 hours of playtime.

**Comment by d87** [comment]
It's just very weird that I've never seen this before, considering it should've been popping up every time someone joins in combat

**Comment by d87** [comment]
Not without a client patch. Well, whatever... I released an update with the bugfix included, so get that if you haven't already https://github.com/rgd87/Aptechka/releases
