### ISSUE TITLE
Suggestion: Sort raid by ______ (Max Health, Class as examples)

### ISSUE THREAD

**Issue by cdmichaelb** [rgd87/Aptechka#67]
If not custom order perhaps sort by class could be Warrior > Melee > Healer > Ranged.

Maybe an option for Class > Max Health as well?

**Comment by d87** [comment]
Unitframes order is managed by protected blizzard code, so addons are limited to what it supports. It's either just role, class or name. And by default it's already sorted by role in aptechka, but classic doesn't have roles except main tank and main assist, which should be assigned manually to work.
Maybe i'll add the option for class sorting later, but that would also imply merging groups, and it kind of a bad idea on classic, especially if you're priest.
