### ISSUE TITLE
Soothing Mist and Jade Serpent Statue

### ISSUE THREAD

**Issue by Haagen-Dazs** [rgd87/Aptechka#7]
The player and statue both have a cast named "Soothing Mist" which have different spell IDs, 115175 for the player and 198533 for the statue.
As the statue spell is not included in the default Aura, I tried to include it as "bars", but then it is overwritten by the players spell.
Is it possible to include this spell in the default Aura so it has its own bar by default?
Thanks

**Comment by d87** [comment]
Not sure yet about adding it by default, but now you can edit internal name on statue's mist to something different, so they won't overwrite each other.
