### ISSUE TITLE
Background color settings & power par

### ISSUE THREAD

**Issue by spamwax** [rgd87/Aptechka#74]
With the following setting, while the power bar is shown, but it doesn't change showing current mana/rage etc....
Is there a setting I am missing to make the power bar work? It seems the Background color multiplier is affecting the power bar.

![image](https://user-images.githubusercontent.com/1251233/116779325-b3bd7200-aa43-11eb-86e9-60123867f650.png)

**Comment by d87** [comment]
Make it like  this
![image](https://user-images.githubusercontent.com/343331/116780054-4130ae80-aaa4-11eb-90a9-9cc242ead904.png)

**Comment by spamwax** [comment]
Thanks :)
Is the "Name Color" part of the beta release? Can I run the beta releases with "tbc" tag on retail?

**Comment by d87** [comment]
Use 9.0.30-beta2.
tbc releases are for tbc only currently, although i plan to soon merge classic, tbc and retail versions into one, since latest changes by blizzard made it possible
