### ISSUE TITLE
Mouse Button 4 doesn't work?

### ISSUE THREAD

**Issue by esjee** [rgd87/Aptechka#9]
Hey, thanks for the great addon. I love using it.

Recently I tried to set up a mouseover keybinding with the back-button on my mouse, which wow seems to indicate as Mouse Button 4. However, while it works fine when I mouseover the player models, it doesn't seem to work with Aptechka's raid frames.

It could be an issue on my end, but I'm not sure what that would be. Do you have any suggestions on getting to the bottom of this?

**Comment by d87** [comment]
Are you using Clique? I just tried and it on live and it seems to be working with MB4
And if you're just using a mouseover macro bound to MB4, then it shouldn't work on any unitframes not just this one, but yeah it would work on models. Unitframes are like buttons, they steal all mouse clicks from 3D world.
Basically, use Clique
