### ISSUE TITLE
LUA Error when Trying to Edit Text1/Text2/Text3 Widgets

### ISSUE THREAD

**Issue by Coch** [rgd87/Aptechka#93]
Receive a LUA error when trying to modify the elements of Text1/Text2/Text3 widgets when using 9.2.8 Beta 1 -- error does not appear in stable (9.2.7) for TBC Classic.

Steps to reproduce:
1. Install 9.2.8 Beta 1 from GitHub
2. Create a new character (why not start clean...)
3. Unload all other addons
4. /apt gui
5. Select widgets
6. Click text1/text2/text3

![image](https://user-images.githubusercontent.com/561098/166681824-e31643a6-c407-4c51-b9d8-66593339206f.png)

**Comment by d87** [comment]
Thanks for reporting, fixed in 9.2.8-beta2
