### ISSUE TITLE
DetailsWrath.3.4.0.0004.146 breaks Aptechka 9.2.9

### ISSUE THREAD

**Issue by maexey** [rgd87/Aptechka#95]
DetailsWrath.3.4.0.0004.146 breaks Aptechka 9.2.9 on the beta server:

Message: Interface\AddOns\Aptechka\Aptechka.lua:566: attempt to call field 'RegisterCallback' (a nil value)
Time: Sat Jul 30 18:03:23 2022
Count: 1
Stack: Interface\AddOns\Aptechka\Aptechka.lua:566: attempt to call field 'RegisterCallback' (a nil value)
[string "@Interface\AddOns\Aptechka\Aptechka.lua"]:566: in function `?'
[string "@Interface\AddOns\Aptechka\Aptechka.lua"]:6: in function <Interface\AddOns\Aptechka\Aptechka.lua:5>

Locals: self = Aptechka {
 0 = <userdata>
 UNIT_MAXPOWER = <function> defined @Interface\AddOns\Aptechka\Aptechka.lua:1476
 loadedAuras = <table> {
 }
 UNIT_AFK_CHANGED = <function> defined @Interface\AddOns\Aptechka\Aptechka.lua:1409
 ForEachFrame = <function> defined @Interface\AddOns\Aptechka\Aptechka.lua:1919
 FrameColorize = <function> defined @Interface\AddOns\Aptechka\Aptechka.lua:1989
 UNIT_MAXHEALTH = <function> defined @Interface\AddOns\Aptechka\Aptechka.lua:1115
 FrameStartTrace = <function> defined @Interface\AddOns\Aptechka\Aptechka.lua:1265
 ScanAuras = <function> defined @Interface\AddOns\Aptechka\Aptechka.lua:3498
 IsGroupEnabled = <function> defined @Interface\AddOns\Aptechka\Aptechka.lua:2323
 FrameUpdateIncomingCast = <function> defined @Interface\AddOns\Aptechka\Aptechka.lua:4240
 FrameUpdateStagger = <function> defined @Interface\AddOns\Aptechka\Aptechka.lua:1705
 RepositionAnchors = <function> defined @Interface\AddOns\Aptechka\Aptechka.lua:2499
 RAID_TARGET_UPDATE = <function> defined @Interface\AddOns\Aptechka\Aptechka.lua:1914
 FrameReadyCheckFinished = <function> defined @Interface\AddOns\Aptechka\Aptechka.lua:1972
 NormalizeWidgetContent = <function> defined @Interface\AddOns\Aptechka\frame.lua:601
 Reconfigure = <function> defined @Interface\AddOns\Aptechka\Aptechka.lua:911
 UNIT_HEAL_PREDICTION = <function> defined @Interface\AddOns\Aptechka\Aptechka.lua:1046
 PLAYER_LOGIN = <function> defined @Interface\AddOns\Aptechka\Aptechka.lua:289
 FixWidgetsAfterUpgrade = <function> defined @Interface\AddOns\Aptechka\frame.lua:93
 UNIT_SPELLCAST_SENT = <function> defined @Interface\AddOns\Aptechka\Aptechka.lua:1675
 UNIT_SPELLCAST_DELAYED = <function> defined @Interface\AddOns\Aptechka\Aptechka.lua:4330
 Lock = <function> defined @Interface\AddOns\Aptechka\Aptechka.lua:3765
 db = <table> {
 }
 ReconfigureTestHeaders = <function> defined @Interface\AddOns\Aptechka\frame.lua:3853
 CreateCoordStatusBar = <function> defined @Interface\AddOns\Aptechka\frame.lua:3709
 SafeCall = <function> defined @Interface\AddOns\Aptechka\Aptechka.lua:2606
 EffectListPostUpdate = <function> defined @Interface\AddOns\Aptechka\Aptechka.lua:3390
 GenerateMergedConfig = <function> defined @Interface\AddOns\Aptechka\Aptechka.lua:706
 ShakeUnitButtons = <function> defined @Interface\AddOns\Aptechka\Aptechka.lua:2133
 TestDebuffSlotsForUnit = <function> defined @Interface\AddOns\Aptechka\Aptechka.lua:3599
 ToggleCompactRaidFrames = <function> defined @Interface\AddOns\Aptechka\Aptechka.lua:827
 FrameUpdateUnitColor = <function> defined @Interface\AddOns\Aptechka\Aptechka.lua:930
 DispelTypeProc = <function> defined @Interface\AddOns\Aptechka\Aptechka.lua:3434
 UpdateWidget = <function> defined @Interface\AddOns\Aptechka\Aptechka.lua:2873
 FrameCheckPhase = <function> defined @Interface\AddOns\Aptechka\Aptechka.lua:1219
 TestCastBars = <function> defined @Interface\AddOns\Aptechka\Aptechka.lua:3646
 UNIT_ENTERED_VEHICLE = <function> defined @Interface\AddOns\Aptechka\Aptechka.lua:1585
 INCOMING_RESURRECT_CHANGED = <function> defined @Interface\AddOns\Aptechka\Aptechka.lua:1214
 FrameUpdateRaidTarget = <function> defined @Interface\AddOns\Aptechka\Aptechka.lua:1906
 GetCurrentGroupType = <function> defined @Interface\AddOns\Aptechka\Aptechka.lua:1841
 ReconfigureProtected = <function> defined @Interface\AddOns\Aptechka\Aptechka.lua:983
 UpdateAbsorbBarConfig = <function> defined @Interface\AddOns\Aptechka\Aptechka.lua:1066
 FrameReadyCheckConfirm = <function> defined @Interface\AddOns\Aptechka\Aptechka.lua:195

**Comment by d87** [comment]
Ok, try disabling Details Names option for now

**Comment by maexey** [comment]
also discussed in Details Discord

"Looked into it. Found the issue, sending a report over to Terciob"

**Comment by Flamanis** [comment]
Issue is fixed on most recent Details Wrath version.

**Comment by maexey** [comment]
can confirm, thanks
