### ISSUE TITLE
WotLK Healer / Damage profile 

### ISSUE THREAD

**Issue by Mongrul** [rgd87/Aptechka#97]
Paladin - when in Holy spec with role selected as Healer,  is only able to use the DAMAGER layout profile.

Is there a way to have this use the Healer layout when Role selected is Healer in the talent pane?  Or is there a way to use a different profiles per spec with Dual Spec?

**Comment by d87** [comment]
Will be fixed in the next update

**Comment by d87** [comment]
https://github.com/rgd87/Aptechka/releases/tag/9.2.11

**Comment by Mongrul** [comment]
That is awesome, thanks for an awesome addon.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Mongrul** [comment]
This doesn't seem to be working on the prepatch.   My paladin will only use the Damage profile.

**Comment by d87** [comment]
Did you set the spec role as healer?

**Comment by Mongrul** [comment]
It looks like the spec reset in my talent pane to tank.  I switched it back to healer and it works great.  Thanks!
